title: WJEC Computer Science Revision
description: GCSE and A Level Computer Science topic guide
baseurl: "/comp-sci"
url: ""
theme: null
remote_theme: null

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: none
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: default
